### PR TITLE
add possibillity to disable service handling

### PR DESCRIPTION
**Pull request by mschiff**
this patch makes it possible to add a pillar item to disable service handling

### CODE REVIEW

**Comment by feiming** [comment]
I believe you based on previous code to add enable_service_control pillar. But that way to get pillar data is wrong. Please refer to https://docs.saltstack.com/en/latest/topics/pillar/#pillar-get-function

**Comment by mschiff** [comment]
I think it is good as it is: the pillar is part of the lookmup data and so pulled in via the

```
merge=salt['pillar.get']('dovecot:lookup')
```

so it can be referenced the same way as all the other variables.

OTOH I had a read somewhere, that for newer salt versions, refenrencing pillar like " pillar.foo.bar" is now fully supported and even more elegant.

**Comment by mschiff** [comment]
Sorry, but you may be right, that my pillar example does nit fit the code.

**Comment by mschiff** [comment]
Hmmm. Please take a look at "{{ dovecot.config.filename }}" for example. Its the same mechanis than what I have used. Should really be ok like this.

Do you still have any concerns?

Like someone just said on IRC: "the dot syntax is new hotness" ;) 

And to be honest: My verison was not "wrong". In earlier versions it was just a matter of taste. And salt['pillar.get'] was better because you could have a default value (which you do not use here).

But in recents salt versions the dot syntax seems to get more and more popular because it is easier to read and easier to write.

**Comment by mschiff** [comment]
Please pull again. The last commit fixes some references to content you seem to have forgotten. Without them the formula was broken for me

TIA

**Comment by feiming** [comment]
Sorry my bad, it's seem i had changed to the old method. I have merged your code

**Pull request merged**
