### PR TITLE
restart dovecot on conf.d/ file change

### PR DESCRIPTION
**Pull request by gregorg**
#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

On conf.d/ file change, dovecot is not restarted.

### CODE REVIEW

**Review by baby-gnu — APPROVED** [review]

**Review by baby-gnu — APPROVED** [review]

**Review by chrean — APPROVED** [review]

**Comment by chrean** [comment]
Is anyone even maintaining this repo anymore?

**Comment by gregorg** [comment]
> Is anyone even maintaining this repo anymore?

If not I can maintain it rather than fork, just set me as maintainer.

**Comment by chrean** [comment]
@gregorg I would love to contribute, too. I have forked my version to add some stuff I needed, but it would be nice if we could make something more official. Not sure anyone is watching these repos, though... Thinking of moving to Ansible these days.

**Comment by jeff350** [comment]
@gregorg @chrean I am watching these repos and willing to work with both of you to get changes in. The saltstack formulas group is working to get all formulas back in a good state, this is just a slow effort. Please reach out to me on the salt slack and we can have a further conversation.

**Pull request merged**
